// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Facade")>]
[<assembly: AssemblyProductAttribute("Logary.Facade")>]
[<assembly: AssemblyVersionAttribute("6.0")>]
[<assembly: AssemblyFileVersionAttribute("6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Facade"
    let [<Literal>] AssemblyProduct = "Logary.Facade"
    let [<Literal>] AssemblyVersion = "6.0"
    let [<Literal>] AssemblyFileVersion = "6.0"
