// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Adapters.AspNetCore")>]
[<assembly: AssemblyProductAttribute("Logary.Adapters.AspNetCore")>]
[<assembly: AssemblyVersionAttribute("6.0.2")>]
[<assembly: AssemblyFileVersionAttribute("6.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Adapters.AspNetCore"
    let [<Literal>] AssemblyProduct = "Logary.Adapters.AspNetCore"
    let [<Literal>] AssemblyVersion = "6.0.2"
    let [<Literal>] AssemblyFileVersion = "6.0.2"
