---
language: csharp
dist: trusty
dotnet: 1.0.1
mono:
  - 4.6.1
  - 4.8.1
  - weekly
  - latest

before_install:
  - rvm install 2.2.3

install:
  - gem install bundler
  - bundle

script:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - bundle exec rake DEBUG=true

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly
   - mono: 4.4.2

env:
  global:
    - TMPDIR=/tmp
