#load "BenchmarkDotNet.Core.fsx" 
#load "Microsoft.CodeAnalysis.CSharp.fsx" 
#load "System.Threading.Tasks.fsx" 
#r "Microsoft.CSharp" 
#r "../../../packages/BenchmarkDotNet.Toolchains.Roslyn/lib/net46/BenchmarkDotNet.Toolchains.Roslyn.dll" 