#load "Google.Apis.Core.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Net.Http.fsx" 
#load "System.Reflection.TypeExtensions.fsx" 
#r "../../../packages/Google.Apis/lib/net45/Google.Apis.dll" 
#r "../../../packages/Google.Apis/lib/net45/Google.Apis.PlatformServices.dll" 