#load "Google.Api.CommonProtos.csx" 
#load "Google.Api.Gax.Grpc.csx" 
#load "Google.Cloud.Logging.Type.csx" 
#load "Grpc.Core.csx" 
#r "../../../packages/Google.Cloud.Logging.V2/lib/net45/Google.Cloud.Logging.V2.dll" 