#load "Google.Api.CommonProtos.csx" 
#load "Google.Api.Gax.csx" 
#load "Google.Apis.Auth.csx" 
#load "Grpc.Auth.csx" 
#load "Grpc.Core.csx" 
#r "../../../packages/Google.Api.Gax.Grpc/lib/net45/Google.Api.Gax.Grpc.dll" 