#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Diagnostics.StackTrace.fsx" 
#load "System.Net.Requests.fsx" 
#r "System.Net.Http" 
#r "../../../packages/Microsoft.ApplicationInsights/lib/net46/Microsoft.ApplicationInsights.dll" 