#load "Microsoft.ApplicationInsights.fsx" 
#load "Microsoft.ApplicationInsights.Agent.Intercept.fsx" 
#load "Microsoft.Extensions.PlatformAbstractions.fsx" 
#load "System.Data.SqlClient.fsx" 
#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Diagnostics.StackTrace.fsx" 
#r "../../../packages/Microsoft.ApplicationInsights.DependencyCollector/lib/net45/Microsoft.AI.DependencyCollector.dll" 