#load "System.IO.fsx" 
#load "System.Net.Primitives.fsx" 
#load "System.Runtime.fsx" 
#load "System.Threading.Tasks.fsx" 
#r "System" 
#r "../../../packages/System.Net.Sockets/lib/net46/System.Net.Sockets.dll" 