#load "System.Collections.fsx" 
#load "System.Globalization.fsx" 
#load "System.IO.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Extensions.fsx" 
#load "System.Security.Principal.fsx" 
#r "../../../packages/System.Security.Claims/lib/net46/System.Security.Claims.dll" 