#load "System.IO.csx" 
#load "System.IO.FileSystem.Primitives.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Handles.csx" 
#load "System.Text.Encoding.csx" 
#load "System.Threading.Tasks.csx" 
#r "mscorlib" 
#r "../../../packages/System.IO.FileSystem/lib/net46/System.IO.FileSystem.dll" 