#load "System.Buffers.fsx" 
#load "System.Memory.fsx" 
#load "System.Security.Cryptography.Cng.fsx" 
#r "System.Security" 
#r "System" 
#r "../../../packages/System.Security.Cryptography.Pkcs/lib/net461/System.Security.Cryptography.Pkcs.dll" 