#load "System.Collections.fsx" 
#load "System.Diagnostics.Debug.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Extensions.fsx" 
#r "System.Core" 