#load "System.Globalization.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Extensions.fsx" 
#load "System.Runtime.InteropServices.fsx" 
#r "../../../packages/System.Globalization.Extensions/lib/net46/System.Globalization.Extensions.dll" 