#load "System.Private.ServiceModel.csx" 
#load "System.ServiceModel.Primitives.csx" 
#r "System.ServiceModel" 
#r "mscorlib" 
#r "../../../packages/System.ServiceModel.Duplex/lib/net461/System.ServiceModel.Duplex.dll" 