#load "System.Configuration.ConfigurationManager.fsx" 
#load "System.DirectoryServices.fsx" 
#load "System.DirectoryServices.Protocols.fsx" 
#load "System.IO.FileSystem.AccessControl.fsx" 
#load "System.Security.AccessControl.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "System.DirectoryServices.AccountManagement" 