#load "System.Globalization.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Extensions.csx" 
#load "System.Runtime.InteropServices.csx" 
#r "mscorlib" 
#r "../../../packages/System.Globalization.Extensions/lib/net46/System.Globalization.Extensions.dll" 