#load "System.IO.fsx" 
#load "System.IO.FileSystem.Primitives.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Handles.fsx" 
#load "System.Text.Encoding.fsx" 
#load "System.Threading.Tasks.fsx" 
#r "../../../packages/System.IO.FileSystem/lib/net46/System.IO.FileSystem.dll" 