#load "System.IO.FileSystem.fsx" 
#load "System.Reflection.fsx" 
#load "System.Reflection.Metadata.fsx" 
#load "System.Runtime.fsx" 
#r "../../../packages/System.Diagnostics.StackTrace/lib/net46/System.Diagnostics.StackTrace.dll" 