namespace PaketLoadScripts

#load "Autofac.csx" 
#load "Newtonsoft.Json.csx" 
#load "NitoAsyncEx.Context.StrongName.csx" 
#load "System.Net.Http.csx" 
#load "System.Reflection.TypeExtensions.csx" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Security.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Core.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.WebLogic.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Streams.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Logic.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Factories.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Credentials.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.Controllers.dll" 
#r "../../../packages/TweetinviAPI/lib/net461/Tweetinvi.dll" 