#load "Google.Apis.csx" 
#load "Google.Apis.Core.csx" 
#load "System.Diagnostics.Process.csx" 
#load "System.Net.Requests.csx" 
#r "../../../packages/Google.Apis.Auth/lib/net45/Google.Apis.Auth.dll" 
#r "../../../packages/Google.Apis.Auth/lib/net45/Google.Apis.Auth.PlatformServices.dll" 