#load "Google.Api.CommonProtos.fsx" 
#load "Google.Api.Gax.Grpc.fsx" 
#load "Google.Cloud.Logging.Type.fsx" 
#load "Grpc.Core.fsx" 
#r "../../../packages/Google.Cloud.Logging.V2/lib/net45/Google.Cloud.Logging.V2.dll" 