#load "System.Buffers.csx" 
#load "System.Memory.csx" 
#load "System.Security.AccessControl.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "mscorlib" 
#r "../../../packages/Microsoft.Win32.Registry/lib/net461/Microsoft.Win32.Registry.dll" 