#load "System.Collections.fsx" 
#load "System.Globalization.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Extensions.fsx" 
#load "System.Threading.fsx" 
#r "System" 
#r "../../../packages/System.Text.RegularExpressions/lib/net463/System.Text.RegularExpressions.dll" 