#load "System.IO.FileSystem.csx" 
#load "System.Reflection.csx" 
#load "System.Reflection.Metadata.csx" 
#load "System.Runtime.csx" 
#r "mscorlib" 
#r "../../../packages/System.Diagnostics.StackTrace/lib/net46/System.Diagnostics.StackTrace.dll" 