#load "System.Security.Cryptography.ProtectedData.csx" 
#r "System" 
#r "System.Configuration" 
#r "System.Xml" 
#r "mscorlib" 
#r "../../../packages/System.Configuration.ConfigurationManager/lib/net461/System.Configuration.ConfigurationManager.dll" 