#load "System.Reflection.csx" 
#load "System.Reflection.Primitives.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Handles.csx" 
#r "System" 
#r "System.Core" 
#r "mscorlib" 
#r "../../../packages/System.Runtime.InteropServices/lib/net463/System.Runtime.InteropServices.dll" 