#load "System.Diagnostics.Debug.fsx" 
#load "System.Globalization.fsx" 
#load "System.IO.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Threading.fsx" 
#load "System.Threading.Tasks.fsx" 
#r "../../../packages/System.Security.Cryptography.Primitives/lib/net46/System.Security.Cryptography.Primitives.dll" 