#load "Microsoft.Win32.Registry.fsx" 
#load "System.Security.Permissions.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#load "System.Threading.AccessControl.fsx" 
#r "System" 
#r "../../../packages/System.Diagnostics.EventLog/lib/net461/System.Diagnostics.EventLog.dll" 