#load "System.ComponentModel.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#r "System" 
#r "mscorlib" 
#r "../../../packages/System.ComponentModel.Primitives/lib/net45/System.ComponentModel.Primitives.dll" 