#load "System.ComponentModel.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#r "System" 
#r "../../../packages/System.ComponentModel.Primitives/lib/net45/System.ComponentModel.Primitives.dll" 