#load "System.Reflection.fsx" 
#load "System.Reflection.Primitives.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Handles.fsx" 
#r "System" 
#r "System.Core" 
#r "../../../packages/System.Runtime.InteropServices/lib/net463/System.Runtime.InteropServices.dll" 