#load "Microsoft.Win32.Registry.fsx" 
#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#load "System.Text.Encoding.CodePages.fsx" 
#r "System.Data" 
#r "System.Xml" 
#r "../../../packages/System.Data.SqlClient/lib/net461/System.Data.SqlClient.dll" 