apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# choose one of:
#- ../as-daemonset
#- ../as-deployment
- ingress.yaml

patchesStrategicMerge:
- deployment.yaml

commonLabels:
  app: logary
  component: rutta

namespace: logary