apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rutta

spec:
  maxReplicas: 9
  minReplicas: 3

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rutta

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80