// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Ingestion.TCP")>]
[<assembly: AssemblyProductAttribute("Logary.Ingestion.TCP")>]
[<assembly: AssemblyVersionAttribute("6.0.1")>]
[<assembly: AssemblyFileVersionAttribute("6.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Ingestion.TCP"
    let [<Literal>] AssemblyProduct = "Logary.Ingestion.TCP"
    let [<Literal>] AssemblyVersion = "6.0.1"
    let [<Literal>] AssemblyFileVersion = "6.0.1"
