// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Adapters.Suave")>]
[<assembly: AssemblyProductAttribute("Logary.Adapters.Suave")>]
[<assembly: AssemblyVersionAttribute("5.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Adapters.Suave"
    let [<Literal>] AssemblyProduct = "Logary.Adapters.Suave"
    let [<Literal>] AssemblyVersion = "5.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0"
