#I "bin/Debug"
#r "FSharp.Actor.dll"
#r "NodaTime.dll"
#r "Newtonsoft.Json.dll"
#r "Logary.dll"
#r "protobuf-net.dll"
#load "../Logary.Targets.Riemann/ProtoBufUtils.fs"
#load "Messages.fs"
#load "Constants.fs"
#load "Types.fs"
#load "Client.fs"
#load "Targets_Heka.fs"
open Logary
open Logary.Configuration
open Logary.Targets
open Logary.Targets.Heka
open Logary.Metrics
open NodaTime
