// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Targets.RabbitMQ")>]
[<assembly: AssemblyProductAttribute("Logary.Targets.RabbitMQ")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2018 Henrik Feldt")>]
[<assembly: AssemblyDescriptionAttribute("Logary is a high performance, multi-target logging, metric and health-check library for mono and .Net.")>]
[<assembly: AssemblyVersionAttribute("5.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Targets.RabbitMQ"
    let [<Literal>] AssemblyProduct = "Logary.Targets.RabbitMQ"
    let [<Literal>] AssemblyCopyright = "Copyright © 2018 Henrik Feldt"
    let [<Literal>] AssemblyDescription = "Logary is a high performance, multi-target logging, metric and health-check library for mono and .Net."
    let [<Literal>] AssemblyVersion = "5.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0"
