// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Adapters.EventStore")>]
[<assembly: AssemblyProductAttribute("Logary.Adapters.EventStore")>]
[<assembly: AssemblyVersionAttribute("6.0")>]
[<assembly: AssemblyFileVersionAttribute("6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Adapters.EventStore"
    let [<Literal>] AssemblyProduct = "Logary.Adapters.EventStore"
    let [<Literal>] AssemblyVersion = "6.0"
    let [<Literal>] AssemblyFileVersion = "6.0"
