#load "Microsoft.Extensions.PlatformAbstractions.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Interactive.Async.fsx" 
#load "System.Net.Http.fsx" 
#r "../../../packages/Google.Api.Gax/lib/netstandard1.3/Google.Api.Gax.dll" 