#load "System.Diagnostics.TextWriterTraceListener.csx" 
#load "System.Diagnostics.TraceSource.csx" 
#load "System.Xml.XPath.csx" 
#load "System.Xml.XPath.XDocument.csx" 
#r "../../../packages/Machine.Specifications/lib/netstandard1.3/Machine.Specifications.dll" 