#load "Microsoft.ApplicationInsights.fsx" 
#load "Microsoft.Extensions.PlatformAbstractions.fsx" 
#load "System.Data.SqlClient.fsx" 
#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Diagnostics.StackTrace.fsx" 
#r "../../../packages/Microsoft.ApplicationInsights.DependencyCollector/lib/netstandard1.6/Microsoft.AI.DependencyCollector.dll" 