#load "System.Reflection.Emit.csx" 
#load "System.Reflection.Emit.ILGeneration.csx" 
#load "System.Reflection.Emit.Lightweight.csx" 
#load "System.Runtime.Serialization.Primitives.csx" 
#load "System.Xml.XmlSerializer.csx" 
#r "../../../packages/protobuf-net/lib/netstandard2.0/protobuf-net.dll" 