#load "System.Linq.csx" 
#load "System.Threading.csx" 
#load "System.Xml.ReaderWriter.csx" 
#load "System.Xml.XDocument.csx" 
#load "System.Xml.XPath.csx" 
#r "../../../packages/System.Xml.XPath.XDocument/lib/netstandard1.3/System.Xml.XPath.XDocument.dll" 