#load "Microsoft.Win32.Registry.csx" 
#load "System.Diagnostics.DiagnosticSource.csx" 
#load "System.Memory.csx" 
#load "System.Security.Principal.Windows.csx" 
#load "System.Text.Encoding.CodePages.csx" 
#r "../../../packages/System.Data.SqlClient/lib/netstandard2.0/System.Data.SqlClient.dll" 