#load "System.Linq.csx" 
#load "System.Reflection.Emit.csx" 
#load "System.Reflection.Emit.ILGeneration.csx" 
#load "System.Text.RegularExpressions.csx" 
#load "System.Threading.csx" 
#load "System.Xml.ReaderWriter.csx" 
#load "System.Xml.XmlDocument.csx" 
#r "../../../packages/System.Xml.XmlSerializer/lib/netstandard1.3/System.Xml.XmlSerializer.dll" 