namespace PaketLoadScripts

#load "Autofac.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "NitoAsyncEx.Context.StrongName.fsx" 
#load "System.Net.Http.fsx" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Security.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Core.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.WebLogic.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Streams.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Logic.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Factories.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Credentials.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.Controllers.dll" 
#r "../../../packages/TweetinviAPI/lib/netstandard1.4/Tweetinvi.dll" 