// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Adapters.Facade")>]
[<assembly: AssemblyProductAttribute("Logary.Adapters.Facade")>]
[<assembly: AssemblyVersionAttribute("5.0.1")>]
[<assembly: AssemblyFileVersionAttribute("5.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Adapters.Facade"
    let [<Literal>] AssemblyProduct = "Logary.Adapters.Facade"
    let [<Literal>] AssemblyVersion = "5.0.1"
    let [<Literal>] AssemblyFileVersion = "5.0.1"
