// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Tests")>]
[<assembly: AssemblyProductAttribute("Logary.Tests")>]
[<assembly: AssemblyVersionAttribute("5.0.1")>]
[<assembly: AssemblyFileVersionAttribute("5.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Tests"
    let [<Literal>] AssemblyProduct = "Logary.Tests"
    let [<Literal>] AssemblyVersion = "5.0.1"
    let [<Literal>] AssemblyFileVersion = "5.0.1"
