// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Proto")>]
[<assembly: AssemblyProductAttribute("Proto")>]
[<assembly: AssemblyVersionAttribute("6.0")>]
[<assembly: AssemblyFileVersionAttribute("6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Proto"
    let [<Literal>] AssemblyProduct = "Proto"
    let [<Literal>] AssemblyVersion = "6.0"
    let [<Literal>] AssemblyFileVersion = "6.0"
