// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logary.Targets.OpsGenie")>]
[<assembly: AssemblyProductAttribute("Logary.Targets.OpsGenie")>]
[<assembly: AssemblyVersionAttribute("6.0.1")>]
[<assembly: AssemblyFileVersionAttribute("6.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logary.Targets.OpsGenie"
    let [<Literal>] AssemblyProduct = "Logary.Targets.OpsGenie"
    let [<Literal>] AssemblyVersion = "6.0.1"
    let [<Literal>] AssemblyFileVersion = "6.0.1"
