#load "Google.Apis.Core.csx" 
#load "Newtonsoft.Json.csx" 
#load "System.Net.Http.csx" 
#load "System.Reflection.TypeExtensions.csx" 
#r "../../../packages/Google.Apis/lib/netstandard1.3/Google.Apis.dll" 