#load "Google.Apis.Core.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Net.Http.fsx" 
#load "System.Reflection.TypeExtensions.fsx" 
#r "../../../packages/Google.Apis/lib/netstandard1.3/Google.Apis.dll" 