#load "System.Threading.csx" 
#load "System.Xml.ReaderWriter.csx" 
#load "System.Xml.XmlDocument.csx" 
#load "System.Xml.XPath.csx" 
#r "../../../packages/System.Xml.XPath.XmlDocument/lib/netstandard1.3/System.Xml.XPath.XmlDocument.dll" 