#load "System.Configuration.ConfigurationManager.fsx" 
#load "System.DirectoryServices.fsx" 
#load "System.DirectoryServices.Protocols.fsx" 
#load "System.IO.FileSystem.AccessControl.fsx" 
#load "System.Security.AccessControl.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "../../../packages/System.DirectoryServices.AccountManagement/lib/netstandard2.0/System.DirectoryServices.AccountManagement.dll" 