#load "System.Linq.csx" 
#load "System.ObjectModel.csx" 
#load "System.Reflection.Emit.csx" 
#load "System.Reflection.Emit.ILGeneration.csx" 
#load "System.Reflection.Emit.Lightweight.csx" 
#load "System.Reflection.TypeExtensions.csx" 
#load "System.Threading.csx" 
#r "../../../packages/System.Linq.Expressions/lib/netstandard1.6/System.Linq.Expressions.dll" 