#load "System.IO.FileSystem.csx" 
#load "System.IO.FileSystem.Primitives.csx" 
#load "System.Text.RegularExpressions.csx" 
#load "System.Threading.Tasks.Extensions.csx" 
#r "../../../packages/System.Xml.ReaderWriter/lib/netstandard1.3/System.Xml.ReaderWriter.dll" 