#load "System.IO.FileSystem.fsx" 
#load "System.IO.FileSystem.Primitives.fsx" 
#load "System.Text.RegularExpressions.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#r "../../../packages/System.Xml.ReaderWriter/lib/netstandard1.3/System.Xml.ReaderWriter.dll" 