#load "System.Linq.fsx" 
#load "System.ObjectModel.fsx" 
#load "System.Reflection.Emit.fsx" 
#load "System.Reflection.Emit.ILGeneration.fsx" 
#load "System.Reflection.Emit.Lightweight.fsx" 
#load "System.Reflection.TypeExtensions.fsx" 
#load "System.Threading.fsx" 
#r "../../../packages/System.Linq.Expressions/lib/netstandard1.6/System.Linq.Expressions.dll" 