#load "System.Linq.csx" 
#load "System.Linq.Expressions.csx" 
#load "System.ObjectModel.csx" 
#load "System.Reflection.Emit.csx" 
#load "System.Reflection.Emit.ILGeneration.csx" 
#load "System.Reflection.TypeExtensions.csx" 
#load "System.Threading.csx" 
#r "../../../packages/System.Dynamic.Runtime/lib/netstandard1.3/System.Dynamic.Runtime.dll" 