#load "Microsoft.Win32.Registry.fsx" 
#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#load "System.Text.Encoding.CodePages.fsx" 
#r "../../../packages/System.Data.SqlClient/lib/netstandard2.0/System.Data.SqlClient.dll" 