#load "System.Threading.fsx" 
#load "System.Xml.ReaderWriter.fsx" 
#load "System.Xml.XmlDocument.fsx" 
#load "System.Xml.XPath.fsx" 
#r "../../../packages/System.Xml.XPath.XmlDocument/lib/netstandard1.3/System.Xml.XPath.XmlDocument.dll" 